#define __COMPILE_0
#define __COMPILE_1
#define __COMPILE_2
#define __COMPILE_3
#define __COMPILE_4
#define __COMPILE_5
#define __COMPILE_6
#define __COMPILE_7
#define __COMPILE_8
#define __COMPILE_9
#define __COMPILE_10
#define __COMPILE_11
#define __COMPILE_12
#define __COMPILE_13
#define __COMPILE_14
#define __COMPILE_15
#define __COMPILE_16
#define __COMPILE_17
#define __COMPILE_18
#define __COMPILE_19
#define __COMPILE_20
#define __COMPILE_21
#define __COMPILE_22
#define __COMPILE_23
#define __COMPILE_24
#define __COMPILE_25
#define __COMPILE_26
#define __COMPILE_27
#define __COMPILE_28
#define __COMPILE_29
#define __COMPILE_30
#define __COMPILE_31
#define __COMPILE_32
#define __COMPILE_33
#define __COMPILE_34
#define __COMPILE_35
#define __COMPILE_36
#define __COMPILE_37
#define __COMPILE_38
#define __COMPILE_39
#define __COMPILE_40
#define __COMPILE_41
#define __COMPILE_42
#define __COMPILE_43
#define __COMPILE_44
#define __COMPILE_45
#define __COMPILE_46
#define __COMPILE_47
#define __COMPILE_48
#define __COMPILE_49
#define __COMPILE_50
#define __COMPILE_51
#define __COMPILE_52
#define __COMPILE_53
#define __COMPILE_54
#define __COMPILE_55
#define __COMPILE_56
#define __COMPILE_57
#define __COMPILE_58
#define __COMPILE_59
#define __COMPILE_60
#define __COMPILE_61
#define __COMPILE_62
#define __COMPILE_63
#define __COMPILE_64
#define __COMPILE_65
#define __COMPILE_66
#define __COMPILE_67
#define __COMPILE_68
#define __COMPILE_69
#define __COMPILE_70
#define __COMPILE_71
#define __COMPILE_72
#define __COMPILE_73
#define __COMPILE_74
#define __COMPILE_75
#define __COMPILE_76
#define __COMPILE_77
#define __COMPILE_78
#define __COMPILE_79
#define __COMPILE_80
#define __COMPILE_81
#define __COMPILE_82
#define __COMPILE_83
#define __COMPILE_84
#define __COMPILE_85
#define __COMPILE_86
#define __COMPILE_87
#define __COMPILE_88
#define __COMPILE_89
#define __COMPILE_90
#define __COMPILE_91
#define __COMPILE_92
#define __COMPILE_93
#define __COMPILE_94
#define __COMPILE_95
#define __COMPILE_96
#define __COMPILE_97
#define __COMPILE_98
#define __COMPILE_99
#define __COMPILE_100
#define __COMPILE_101
#define __COMPILE_102
#define __COMPILE_103
#define __COMPILE_104
#define __COMPILE_105
#define __COMPILE_106
#define __COMPILE_107
#define __COMPILE_108
#define __COMPILE_109
#define __COMPILE_110
#define __COMPILE_111
#define __COMPILE_112
#define __COMPILE_113
#define __COMPILE_114
#define __COMPILE_115
#define __COMPILE_116
#define __COMPILE_117
#define __COMPILE_118
#define __COMPILE_119
#define __COMPILE_120
#define __COMPILE_121
#define __COMPILE_122
#define __COMPILE_123
#define __COMPILE_124
#define __COMPILE_125
#define __COMPILE_126
#define __COMPILE_127
#define __COMPILE_128
#define __COMPILE_129
#define __COMPILE_130
#define __COMPILE_131
#define __COMPILE_132
#define __COMPILE_133
#define __COMPILE_134
#define __COMPILE_135
#define __COMPILE_136
#define __COMPILE_137
#define __COMPILE_138
#define __COMPILE_139
#define __COMPILE_140
#define __COMPILE_141
#define __COMPILE_142
#define __COMPILE_143
#define __COMPILE_144
#define __COMPILE_145
#define __COMPILE_146
#define __COMPILE_147
#define __COMPILE_148
#define __COMPILE_149
#define __COMPILE_150
#define __COMPILE_151
#define __COMPILE_152
#define __COMPILE_153
#define __COMPILE_154
#define __COMPILE_155
#define __COMPILE_156
#define __COMPILE_157
#define __COMPILE_158
#define __COMPILE_159
#define __COMPILE_160
#define __COMPILE_161
#define __COMPILE_162
#define __COMPILE_163
#define __COMPILE_164
#define __COMPILE_165
#define __COMPILE_166
#define __COMPILE_167
#define __COMPILE_168
#define __COMPILE_169
#define __COMPILE_170
#define __COMPILE_171
#define __COMPILE_172
#define __COMPILE_173
#define __COMPILE_174
#define __COMPILE_175
#define __COMPILE_176
#define __COMPILE_177
#define __COMPILE_178
#define __COMPILE_179
#define __COMPILE_180
#define __COMPILE_181
#define __COMPILE_182
#define __COMPILE_183
// compile_fin
int __get_mutant(); int __is_neg(const char *location,char *lid,int count, ...); int __abst_hole(); char *__stat_write_init(const char *func_name);void __write_stat(char *str,const char *var_name,void *var_addr,int size); void __stat_file_close(const char *func_name,char *str);long long __mutate(const long long,const char *,const char *); int __trident_choice(char* lid, char* typestr,int* rvals, char** rvals_ids, int rvals_size,int** lvals, char** lvals_ids, int lvals_size);int __trident_output(char* id, char* typestr, int value);float fabs_trident(float a);int __choose(const char *);void *__var_select(unsigned int var_count,void *vars[]);void *__var_select_2(unsigned int var_count,void *vars[]);long long __const_select(unsigned int const_count, ...);void* memset(void*, int, unsigned long); 
/* Generated by re2c 0.13.5 on Mon May 31 11:07:50 2010 */
#line 1 "ext/standard/url_scanner_ex.re"
/*
  +----------------------------------------------------------------------+
  | PHP Version 6                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997-2006 The PHP Group                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: Sascha Schumann <sascha@schumann.cx>                         |
  +----------------------------------------------------------------------+
*/

/* $Id$ */

#include "php.h"

#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#ifdef HAVE_LIMITS_H
#include <limits.h>
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "php_ini.h"
#include "php_globals.h"
#define STATE_TAG SOME_OTHER_STATE_TAG
#include "basic_functions.h"
#include "url.h"
#undef STATE_TAG

#define url_scanner url_scanner_ex

#include "php_smart_str.h"

static PHP_INI_MH(OnUpdateTags)
{
	url_adapt_state_ex_t *ctx;
	char *key;
	char *lasts;
	char *tmp;
	
	ctx = &BG(url_adapt_state_ex);
	
	tmp = estrndup(new_value, new_value_length);
	
	if (ctx->tags)
		zend_hash_destroy(ctx->tags);
	else
		ctx->tags = malloc(sizeof(HashTable));
	
	zend_hash_init(ctx->tags, 0, NULL, NULL, 1);
	
	for (key = php_strtok_r(tmp, ",", &lasts);
			key;
			key = php_strtok_r(NULL, ",", &lasts)) {
		char *val;

		val = strchr(key, '=');
		if (val) {
			char *q;
			int keylen;
			
			*val++ = '\0';
			for (q = key; *q; q++)
				*q = tolower(*q);
			keylen = q - key;
			/* key is stored withOUT NUL
			   val is stored WITH    NUL */
			zend_hash_add(ctx->tags, key, keylen, val, strlen(val)+1, NULL);
		}
	}

	efree(tmp);

	return SUCCESS;
}

PHP_INI_BEGIN()
	STD_PHP_INI_ENTRY("url_rewriter.tags", "a=href,area=href,frame=src,form=,fieldset=", PHP_INI_ALL, OnUpdateTags, url_adapt_state_ex, php_basic_globals, basic_globals)
PHP_INI_END()

#line 98 "ext/standard/url_scanner_ex.re"


#define YYFILL(n) goto done
#define YYCTYPE unsigned char
#define YYCURSOR p
#define YYLIMIT q
#define YYMARKER r
	
static inline void append_modified_url(smart_str *url, smart_str *dest, smart_str *url_app, const char *separator)
{
	register const char *p, *q;
	const char *bash = NULL;
	const char *sep = "?";
	
	q = (p = url->c) + url->len;

scan:

#line 114 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0, 128, 128, 128, 128,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};

	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy8;
	}
	if (yych <= '9') goto yy6;
	if (yych >= ';') goto yy4;
	++YYCURSOR;
#line 116 "ext/standard/url_scanner_ex.re"
	{ smart_str_append(dest, url); return; }
#line 162 "ext/standard/url_scanner_ex.c"
yy4:
	++YYCURSOR;
#line 117 "ext/standard/url_scanner_ex.re"
	{ sep = separator; goto scan; }
#line 167 "ext/standard/url_scanner_ex.c"
yy6:
	++YYCURSOR;
#line 118 "ext/standard/url_scanner_ex.re"
	{ bash = p - 1; goto done; }
#line 172 "ext/standard/url_scanner_ex.c"
yy8:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy8;
	}
#line 119 "ext/standard/url_scanner_ex.re"
	{ goto scan; }
#line 182 "ext/standard/url_scanner_ex.c"
}
#line 120 "ext/standard/url_scanner_ex.re"

done:
	
	/* Don't modify URLs of the format "#mark" */
	if (bash && bash - url->c == 0) {
		smart_str_append(dest, url);
		return;
	}

	if (bash)
		smart_str_appendl(dest, url->c, bash - url->c);
	else
		smart_str_append(dest, url);

	smart_str_appends(dest, sep);
	smart_str_append(dest, url_app);

	if (bash)
		smart_str_appendl(dest, bash, q - bash);
}


#undef YYFILL
#undef YYCTYPE
#undef YYCURSOR
#undef YYLIMIT
#undef YYMARKER

static inline void tag_arg(url_adapt_state_ex_t *ctx, char quotes, char type TSRMLS_DC)
{
	char f = 0;

	if (strncasecmp(ctx->arg.c, ctx->lookup_data, ctx->arg.len) == 0)
		f = 1;

	if (quotes)
		smart_str_appendc(&ctx->result, type);
	if (f) {
		append_modified_url(&ctx->val, &ctx->result, &ctx->url_app, PG(arg_separator).output);
	} else {
		smart_str_append(&ctx->result, &ctx->val);
	}
	if (quotes)
		smart_str_appendc(&ctx->result, type);
}

enum {
	STATE_PLAIN = 0,
	STATE_TAG,
	STATE_NEXT_ARG,
	STATE_ARG,
	STATE_BEFORE_VAL,
	STATE_VAL
};

#define YYFILL(n) goto stop
#define YYCTYPE unsigned char
#define YYCURSOR xp
#define YYLIMIT end
#define YYMARKER q
#define STATE ctx->state

#define STD_PARA url_adapt_state_ex_t *ctx, char *start, char *YYCURSOR TSRMLS_DC
#define STD_ARGS ctx, start, xp TSRMLS_CC

#if SCANNER_DEBUG
#define scdebug(x) printf x
#else
#define scdebug(x)
#endif

static inline void passthru(STD_PARA) 
{
	scdebug(("appending %d chars, starting with %c\n", YYCURSOR-start, *start));
	smart_str_appendl(&ctx->result, start, YYCURSOR - start);
}

/*
 * This function appends a hidden input field after a <form> or
 * <fieldset>.  The latter is important for XHTML.
 */

static void handle_form(STD_PARA) 
{
	int doit = 0;

	if (ctx->form_app.len > 0) {
		switch (ctx->tag.len) {
			case sizeof("form") - 1:
				if (!strncasecmp(ctx->tag.c, "form", sizeof("form") - 1)) {
					doit = 1;		
				}
				if (doit && ctx->val.c && ctx->lookup_data && *ctx->lookup_data) {
					char *e, *p = zend_memnstr(ctx->val.c, "://", sizeof("://") - 1, ctx->val.c + ctx->val.len);
					if (p) {
						e = memchr(p, '/', (ctx->val.c + ctx->val.len) - p);
						if (!e) {
							e = ctx->val.c + ctx->val.len;
						}
						if ((e - p) && strncasecmp(p, ctx->lookup_data, (e - p))) {
							doit = 0;
						}
					}
				}
				break;

			case sizeof("fieldset") - 1:
				if (!strncasecmp(ctx->tag.c, "fieldset", sizeof("fieldset") - 1)) {
					doit = 1;		
				}
				break;
		}

		if (doit)
			smart_str_append(&ctx->result, &ctx->form_app);
	}
}

/*
 *  HANDLE_TAG copies the HTML Tag and checks whether we 
 *  have that tag in our table. If we might modify it,
 *  we continue to scan the tag, otherwise we simply copy the complete
 *  HTML stuff to the result buffer.
 */

static inline void handle_tag(STD_PARA) 
{
	int ok = 0;
	unsigned int i;

	ctx->tag.len = 0;
	smart_str_appendl(&ctx->tag, start, YYCURSOR - start);
	for (i = 0; i < ctx->tag.len; i++)
		ctx->tag.c[i] = tolower((int)(unsigned char)ctx->tag.c[i]);
	if (zend_hash_find(ctx->tags, ctx->tag.c, ctx->tag.len, (void **) &ctx->lookup_data) == SUCCESS)
		ok = 1;
	STATE = ok ? STATE_NEXT_ARG : STATE_PLAIN;
}

static inline void handle_arg(STD_PARA) 
{
	ctx->arg.len = 0;
	smart_str_appendl(&ctx->arg, start, YYCURSOR - start);
}

static inline void handle_val(STD_PARA, char quotes, char type) 
{
	smart_str_setl(&ctx->val, start + quotes, YYCURSOR - start - quotes * 2);
	tag_arg(ctx, quotes, type TSRMLS_CC);
}

static inline void xx_mainloop(url_adapt_state_ex_t *ctx, const char *newdata, size_t newlen TSRMLS_DC)
{
	char *end, *q;
	char *xp;
	char *start;
	int rest;

	smart_str_appendl(&ctx->buf, newdata, newlen);
	
	YYCURSOR = ctx->buf.c;
	YYLIMIT = ctx->buf.c + ctx->buf.len;

	switch (STATE) {
		case STATE_PLAIN: goto state_plain;
		case STATE_TAG: goto state_tag;
		case STATE_NEXT_ARG: goto state_next_arg;
		case STATE_ARG: goto state_arg;
		case STATE_BEFORE_VAL: goto state_before_val;
		case STATE_VAL: goto state_val;
	}
	

state_plain_begin:
	STATE = STATE_PLAIN;
	
state_plain:
	start = YYCURSOR;

#line 364 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128,   0, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
	};
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy15;
	}
	++YYCURSOR;
#line 299 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); STATE = STATE_TAG; goto state_tag; }
#line 409 "ext/standard/url_scanner_ex.c"
yy15:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy15;
	}
#line 300 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); goto state_plain; }
#line 419 "ext/standard/url_scanner_ex.c"
}
#line 301 "ext/standard/url_scanner_ex.re"


state_tag:	
	start = YYCURSOR;

#line 427 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0, 128,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych <= '@') {
		if (yych != ':') goto yy22;
	} else {
		if (yych <= 'Z') goto yy20;
		if (yych <= '`') goto yy22;
		if (yych >= '{') goto yy22;
	}
yy20:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy25;
yy21:
#line 306 "ext/standard/url_scanner_ex.re"
	{ handle_tag(STD_ARGS); /* Sets STATE */; passthru(STD_ARGS); if (STATE == STATE_PLAIN) goto state_plain; else goto state_next_arg; }
#line 480 "ext/standard/url_scanner_ex.c"
yy22:
	++YYCURSOR;
#line 307 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); goto state_plain_begin; }
#line 485 "ext/standard/url_scanner_ex.c"
yy24:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy25:
	if (yybm[0+yych] & 128) {
		goto yy24;
	}
	goto yy21;
}
#line 308 "ext/standard/url_scanner_ex.re"


state_next_arg_begin:
	STATE = STATE_NEXT_ARG;
	
state_next_arg:
	start = YYCURSOR;

#line 505 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128,   0, 128,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy34;
			if (yych <= '\v') goto yy30;
			goto yy34;
		} else {
			if (yych <= '\r') goto yy30;
			if (yych <= 0x1F) goto yy34;
			goto yy30;
		}
	} else {
		if (yych <= '@') {
			if (yych != '>') goto yy34;
		} else {
			if (yych <= 'Z') goto yy32;
			if (yych <= '`') goto yy34;
			if (yych <= 'z') goto yy32;
			goto yy34;
		}
	}
	++YYCURSOR;
#line 316 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); handle_form(STD_ARGS); goto state_plain_begin; }
#line 567 "ext/standard/url_scanner_ex.c"
yy30:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy37;
yy31:
#line 317 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); goto state_next_arg; }
#line 575 "ext/standard/url_scanner_ex.c"
yy32:
	++YYCURSOR;
#line 318 "ext/standard/url_scanner_ex.re"
	{ --YYCURSOR; STATE = STATE_ARG; goto state_arg; }
#line 580 "ext/standard/url_scanner_ex.c"
yy34:
	++YYCURSOR;
#line 319 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); goto state_plain_begin; }
#line 585 "ext/standard/url_scanner_ex.c"
yy36:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy37:
	if (yybm[0+yych] & 128) {
		goto yy36;
	}
	goto yy31;
}
#line 320 "ext/standard/url_scanner_ex.re"


state_arg:
	start = YYCURSOR;

#line 602 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0, 128,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych <= '@') goto yy42;
	if (yych <= 'Z') goto yy40;
	if (yych <= '`') goto yy42;
	if (yych >= '{') goto yy42;
yy40:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy45;
yy41:
#line 325 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); handle_arg(STD_ARGS); STATE = STATE_BEFORE_VAL; goto state_before_val; }
#line 652 "ext/standard/url_scanner_ex.c"
yy42:
	++YYCURSOR;
#line 326 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); STATE = STATE_NEXT_ARG; goto state_next_arg; }
#line 657 "ext/standard/url_scanner_ex.c"
yy44:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy45:
	if (yybm[0+yych] & 128) {
		goto yy44;
	}
	goto yy41;
}
#line 327 "ext/standard/url_scanner_ex.re"


state_before_val:
	start = YYCURSOR;

#line 674 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych == ' ') goto yy48;
	if (yych == '=') goto yy50;
	goto yy52;
yy48:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == ' ') goto yy55;
	if (yych == '=') goto yy53;
yy49:
#line 333 "ext/standard/url_scanner_ex.re"
	{ --YYCURSOR; goto state_next_arg_begin; }
#line 723 "ext/standard/url_scanner_ex.c"
yy50:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy54;
yy51:
#line 332 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); STATE = STATE_VAL; goto state_val; }
#line 731 "ext/standard/url_scanner_ex.c"
yy52:
	yych = *++YYCURSOR;
	goto yy49;
yy53:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy54:
	if (yybm[0+yych] & 128) {
		goto yy53;
	}
	goto yy51;
yy55:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == ' ') goto yy55;
	if (yych == '=') goto yy53;
	YYCURSOR = YYMARKER;
	goto yy49;
}
#line 334 "ext/standard/url_scanner_ex.re"



state_val:
	start = YYCURSOR;

#line 760 "ext/standard/url_scanner_ex.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 160, 160, 248, 248, 160, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		160, 248,  56, 248, 248, 248, 248, 200, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248,   0, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
		248, 248, 248, 248, 248, 248, 248, 248, 
	};
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy63;
			if (yych <= '\n') goto yy64;
			goto yy63;
		} else {
			if (yych <= '\r') goto yy64;
			if (yych <= 0x1F) goto yy63;
			goto yy64;
		}
	} else {
		if (yych <= '&') {
			if (yych != '"') goto yy63;
		} else {
			if (yych <= '\'') goto yy62;
			if (yych == '>') goto yy64;
			goto yy63;
		}
	}
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy77;
yy61:
#line 342 "ext/standard/url_scanner_ex.re"
	{ handle_val(STD_ARGS, 0, ' '); goto state_next_arg_begin; }
#line 823 "ext/standard/url_scanner_ex.c"
yy62:
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy69;
yy63:
	yych = *++YYCURSOR;
	goto yy67;
yy64:
	++YYCURSOR;
#line 343 "ext/standard/url_scanner_ex.re"
	{ passthru(STD_ARGS); goto state_next_arg_begin; }
#line 834 "ext/standard/url_scanner_ex.c"
yy66:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy67:
	if (yybm[0+yych] & 8) {
		goto yy66;
	}
	goto yy61;
yy68:
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
yy69:
	if (yybm[0+yych] & 16) {
		goto yy68;
	}
	if (yych <= '&') goto yy72;
	if (yych >= '(') goto yy61;
	++YYCURSOR;
	if (yybm[0+(yych = *YYCURSOR)] & 8) {
		goto yy66;
	}
yy71:
#line 341 "ext/standard/url_scanner_ex.re"
	{ handle_val(STD_ARGS, 1, '\''); goto state_next_arg_begin; }
#line 861 "ext/standard/url_scanner_ex.c"
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy72;
	}
	if (yych <= '=') goto yy75;
yy74:
	YYCURSOR = YYMARKER;
	goto yy61;
yy75:
	yych = *++YYCURSOR;
	goto yy71;
yy76:
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
yy77:
	if (yybm[0+yych] & 64) {
		goto yy76;
	}
	if (yych <= '!') goto yy80;
	if (yych >= '#') goto yy61;
	++YYCURSOR;
	if (yybm[0+(yych = *YYCURSOR)] & 8) {
		goto yy66;
	}
yy79:
#line 340 "ext/standard/url_scanner_ex.re"
	{ handle_val(STD_ARGS, 1, '"'); goto state_next_arg_begin; }
#line 893 "ext/standard/url_scanner_ex.c"
yy80:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy80;
	}
	if (yych >= '>') goto yy74;
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy79;
}
#line 344 "ext/standard/url_scanner_ex.re"


stop:
	rest = YYLIMIT - start;
	scdebug(("stopped in state %d at pos %d (%d:%c) %d\n", STATE, YYCURSOR - ctx->buf.c, *YYCURSOR, *YYCURSOR, rest));
	/* XXX: Crash avoidance. Need to work with reporter to figure out what goes wrong */	
	if (rest < 0) rest = 0;
	
	if (rest) memmove(ctx->buf.c, start, rest);
	ctx->buf.len = rest;
}

char *php_url_scanner_adapt_single_url(const char *url, size_t urllen, const char *name, const char *value, size_t *newlen TSRMLS_DC)
{
	smart_str surl = {0};
	smart_str buf = {0};
	smart_str url_app = {0};

	smart_str_setl(&surl, url, urllen);

	smart_str_appends(&url_app, name);
	smart_str_appendc(&url_app, '=');
	smart_str_appends(&url_app, value);

	append_modified_url(&surl, &buf, &url_app, PG(arg_separator).output);

	smart_str_0(&buf);
	if (newlen) *newlen = buf.len;

	smart_str_free(&url_app);

	return buf.c;
}


static char *url_adapt_ext(const char *src, size_t srclen, size_t *newlen, zend_bool do_flush TSRMLS_DC)
{
	url_adapt_state_ex_t *ctx;
	char *retval;

	ctx = &BG(url_adapt_state_ex);

	xx_mainloop(ctx, src, srclen TSRMLS_CC);

	*newlen = ctx->result.len;
	if (!ctx->result.c) {
		smart_str_appendl(&ctx->result, "", 0);
	}
	smart_str_0(&ctx->result);
	if (do_flush) {
		smart_str_appendl(&ctx->result, ctx->buf.c, ctx->buf.len);
		*newlen += ctx->buf.len;
		smart_str_free(&ctx->buf);
	}
	retval = ctx->result.c;
	ctx->result.c = NULL;
	ctx->result.len = 0;
	return retval;
}

static int php_url_scanner_ex_activate(TSRMLS_D)
{
	url_adapt_state_ex_t *ctx;
	
	ctx = &BG(url_adapt_state_ex);

	memset(ctx, 0, ((size_t) &((url_adapt_state_ex_t *)0)->tags));

	return SUCCESS;
}

static int php_url_scanner_ex_deactivate(TSRMLS_D)
{
	url_adapt_state_ex_t *ctx;
	
	ctx = &BG(url_adapt_state_ex);

	smart_str_free(&ctx->result);
	smart_str_free(&ctx->buf);
	smart_str_free(&ctx->tag);
	smart_str_free(&ctx->arg);

	return SUCCESS;
}

static void php_url_scanner_output_handler(char *output, uint output_len, char **handled_output, uint *handled_output_len, int mode TSRMLS_DC)
{
	size_t len;

	if (BG(url_adapt_state_ex).url_app.len != 0) {
		*handled_output = url_adapt_ext(output, output_len, &len, (zend_bool) (mode & (PHP_OUTPUT_HANDLER_END | PHP_OUTPUT_HANDLER_CONT | PHP_OUTPUT_HANDLER_FLUSH | PHP_OUTPUT_HANDLER_FINAL) ? 1 : 0) TSRMLS_CC);
		if (sizeof(uint) < sizeof(size_t)) {
			if (len > UINT_MAX)
				len = UINT_MAX;
		}
		*handled_output_len = len;
	} else if (BG(url_adapt_state_ex).url_app.len == 0) {
		url_adapt_state_ex_t *ctx = &BG(url_adapt_state_ex);
		//prophet generated patch
		{
		int __choose0 = __choose("__SWITCH0");
		if (__choose0 == 0)
		{}
		#ifdef __COMPILE_0
		else if (__choose0 == 1)
		{
		//AddIfStmtKind
		if (!(basic_globals.url_adapt_state_ex).active) {
		    php_url_scanner_ex_activate();
		    php_output_start_internal(("URL-Rewriter"), (sizeof ("URL-Rewriter") - 1), php_url_scanner_output_handler, 0, 112);
		    (basic_globals.url_adapt_state_ex).active = 1;
		}
		}
		#endif
		#ifdef __COMPILE_1
		else if (__choose0 == 2)
		{
		//AddIfStmtKind
		if ((basic_globals.url_adapt_state_ex).active) {
		    php_url_scanner_ex_deactivate();
		    (basic_globals.url_adapt_state_ex).active = 0;
		}
		}
		#endif
		#ifdef __COMPILE_2
		else if (__choose0 == 3)
		{
		//AddIfStmtKind
		if (len > (2147483647 * 2U + 1U))
		    len = (2147483647 * 2U + 1U);
		}
		#endif
		#ifdef __COMPILE_3
		else if (__choose0 == 4)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).active, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).active)));
		}
		#endif
		#ifdef __COMPILE_4
		else if (__choose0 == 5)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).arg, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).arg)));
		}
		#endif
		#ifdef __COMPILE_5
		else if (__choose0 == 6)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).buf, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).buf)));
		}
		#endif
		#ifdef __COMPILE_6
		else if (__choose0 == 7)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).form_app, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).form_app)));
		}
		#endif
		#ifdef __COMPILE_7
		else if (__choose0 == 8)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).lookup_data, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).lookup_data)));
		}
		#endif
		#ifdef __COMPILE_8
		else if (__choose0 == 9)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).result, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).result)));
		}
		#endif
		#ifdef __COMPILE_9
		else if (__choose0 == 10)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).state, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).state)));
		}
		#endif
		#ifdef __COMPILE_10
		else if (__choose0 == 11)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).tag, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).tag)));
		}
		#endif
		#ifdef __COMPILE_11
		else if (__choose0 == 12)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).tags, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).tags)));
		}
		#endif
		#ifdef __COMPILE_12
		else if (__choose0 == 13)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).url_app, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).url_app)));
		}
		#endif
		#ifdef __COMPILE_13
		else if (__choose0 == 14)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).url_app.a, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).url_app.a)));
		}
		#endif
		#ifdef __COMPILE_14
		else if (__choose0 == 15)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).url_app.c, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).url_app.c)));
		}
		#endif
		#ifdef __COMPILE_15
		else if (__choose0 == 16)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).url_app.len, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).url_app.len)));
		}
		#endif
		#ifdef __COMPILE_16
		else if (__choose0 == 17)
		{
		//AddInitKind
		memset(&(basic_globals.url_adapt_state_ex).val, 0, sizeof (*(&(basic_globals.url_adapt_state_ex).val)));
		}
		#endif
		#ifdef __COMPILE_17
		else if (__choose0 == 18)
		{
		//AddInitKind
		memset(&basic_globals.CurrentLStatFile, 0, sizeof (*(&basic_globals.CurrentLStatFile)));
		}
		#endif
		#ifdef __COMPILE_18
		else if (__choose0 == 19)
		{
		//AddInitKind
		memset(&basic_globals.CurrentStatFile, 0, sizeof (*(&basic_globals.CurrentStatFile)));
		}
		#endif
		#ifdef __COMPILE_19
		else if (__choose0 == 20)
		{
		//AddInitKind
		memset(&basic_globals.active_ini_file_section, 0, sizeof (*(&basic_globals.active_ini_file_section)));
		}
		#endif
		#ifdef __COMPILE_20
		else if (__choose0 == 21)
		{
		//AddInitKind
		memset(&basic_globals.array_walk_fci, 0, sizeof (*(&basic_globals.array_walk_fci)));
		}
		#endif
		#ifdef __COMPILE_21
		else if (__choose0 == 22)
		{
		//AddInitKind
		memset(&basic_globals.array_walk_fci_cache, 0, sizeof (*(&basic_globals.array_walk_fci_cache)));
		}
		#endif
		#ifdef __COMPILE_22
		else if (__choose0 == 23)
		{
		//AddInitKind
		memset(&basic_globals.incomplete_class, 0, sizeof (*(&basic_globals.incomplete_class)));
		}
		#endif
		#ifdef __COMPILE_23
		else if (__choose0 == 24)
		{
		//AddInitKind
		memset(&basic_globals.left, 0, sizeof (*(&basic_globals.left)));
		}
		#endif
		#ifdef __COMPILE_24
		else if (__choose0 == 25)
		{
		//AddInitKind
		memset(&basic_globals.locale_string, 0, sizeof (*(&basic_globals.locale_string)));
		}
		#endif
		#ifdef __COMPILE_25
		else if (__choose0 == 26)
		{
		//AddInitKind
		memset(&basic_globals.lssb, 0, sizeof (*(&basic_globals.lssb)));
		}
		#endif
		#ifdef __COMPILE_26
		else if (__choose0 == 27)
		{
		//AddInitKind
		memset(&basic_globals.mmap_file, 0, sizeof (*(&basic_globals.mmap_file)));
		}
		#endif
		#ifdef __COMPILE_27
		else if (__choose0 == 28)
		{
		//AddInitKind
		memset(&basic_globals.mmap_len, 0, sizeof (*(&basic_globals.mmap_len)));
		}
		#endif
		#ifdef __COMPILE_28
		else if (__choose0 == 29)
		{
		//AddInitKind
		memset(&basic_globals.mt_rand_is_seeded, 0, sizeof (*(&basic_globals.mt_rand_is_seeded)));
		}
		#endif
		#ifdef __COMPILE_29
		else if (__choose0 == 30)
		{
		//AddInitKind
		memset(&basic_globals.next, 0, sizeof (*(&basic_globals.next)));
		}
		#endif
		#ifdef __COMPILE_30
		else if (__choose0 == 31)
		{
		//AddInitKind
		memset(&basic_globals.page_gid, 0, sizeof (*(&basic_globals.page_gid)));
		}
		#endif
		#ifdef __COMPILE_31
		else if (__choose0 == 32)
		{
		//AddInitKind
		memset(&basic_globals.page_inode, 0, sizeof (*(&basic_globals.page_inode)));
		}
		#endif
		#ifdef __COMPILE_32
		else if (__choose0 == 33)
		{
		//AddInitKind
		memset(&basic_globals.page_mtime, 0, sizeof (*(&basic_globals.page_mtime)));
		}
		#endif
		#ifdef __COMPILE_33
		else if (__choose0 == 34)
		{
		//AddInitKind
		memset(&basic_globals.page_uid, 0, sizeof (*(&basic_globals.page_uid)));
		}
		#endif
		#ifdef __COMPILE_34
		else if (__choose0 == 35)
		{
		//AddInitKind
		memset(&basic_globals.putenv_ht, 0, sizeof (*(&basic_globals.putenv_ht)));
		}
		#endif
		#ifdef __COMPILE_35
		else if (__choose0 == 36)
		{
		//AddInitKind
		memset(&basic_globals.rand_is_seeded, 0, sizeof (*(&basic_globals.rand_is_seeded)));
		}
		#endif
		#ifdef __COMPILE_36
		else if (__choose0 == 37)
		{
		//AddInitKind
		memset(&basic_globals.rand_seed, 0, sizeof (*(&basic_globals.rand_seed)));
		}
		#endif
		#ifdef __COMPILE_37
		else if (__choose0 == 38)
		{
		//AddInitKind
		memset(&basic_globals.serialize, 0, sizeof (*(&basic_globals.serialize)));
		}
		#endif
		#ifdef __COMPILE_38
		else if (__choose0 == 39)
		{
		//AddInitKind
		memset(&basic_globals.ssb, 0, sizeof (*(&basic_globals.ssb)));
		}
		#endif
		#ifdef __COMPILE_39
		else if (__choose0 == 40)
		{
		//AddInitKind
		memset(&basic_globals.state, 0, sizeof (*(&basic_globals.state)));
		}
		#endif
		#ifdef __COMPILE_40
		else if (__choose0 == 41)
		{
		//AddInitKind
		memset(&basic_globals.str_ebuf, 0, sizeof (*(&basic_globals.str_ebuf)));
		}
		#endif
		#ifdef __COMPILE_41
		else if (__choose0 == 42)
		{
		//AddInitKind
		memset(&basic_globals.strtok_last, 0, sizeof (*(&basic_globals.strtok_last)));
		}
		#endif
		#ifdef __COMPILE_42
		else if (__choose0 == 43)
		{
		//AddInitKind
		memset(&basic_globals.strtok_len, 0, sizeof (*(&basic_globals.strtok_len)));
		}
		#endif
		#ifdef __COMPILE_43
		else if (__choose0 == 44)
		{
		//AddInitKind
		memset(&basic_globals.strtok_string, 0, sizeof (*(&basic_globals.strtok_string)));
		}
		#endif
		#ifdef __COMPILE_44
		else if (__choose0 == 45)
		{
		//AddInitKind
		memset(&basic_globals.strtok_table, 0, sizeof (*(&basic_globals.strtok_table)));
		}
		#endif
		#ifdef __COMPILE_45
		else if (__choose0 == 46)
		{
		//AddInitKind
		memset(&basic_globals.strtok_zval, 0, sizeof (*(&basic_globals.strtok_zval)));
		}
		#endif
		#ifdef __COMPILE_46
		else if (__choose0 == 47)
		{
		//AddInitKind
		memset(&basic_globals.syslog_device, 0, sizeof (*(&basic_globals.syslog_device)));
		}
		#endif
		#ifdef __COMPILE_47
		else if (__choose0 == 48)
		{
		//AddInitKind
		memset(&basic_globals.umask, 0, sizeof (*(&basic_globals.umask)));
		}
		#endif
		#ifdef __COMPILE_48
		else if (__choose0 == 49)
		{
		//AddInitKind
		memset(&basic_globals.unserialize, 0, sizeof (*(&basic_globals.unserialize)));
		}
		#endif
		#ifdef __COMPILE_49
		else if (__choose0 == 50)
		{
		//AddInitKind
		memset(&basic_globals.url_adapt_state_ex, 0, sizeof (*(&basic_globals.url_adapt_state_ex)));
		}
		#endif
		#ifdef __COMPILE_50
		else if (__choose0 == 51)
		{
		//AddInitKind
		memset(&basic_globals.user_compare_fci, 0, sizeof (*(&basic_globals.user_compare_fci)));
		}
		#endif
		#ifdef __COMPILE_51
		else if (__choose0 == 52)
		{
		//AddInitKind
		memset(&basic_globals.user_compare_fci_cache, 0, sizeof (*(&basic_globals.user_compare_fci_cache)));
		}
		#endif
		#ifdef __COMPILE_52
		else if (__choose0 == 53)
		{
		//AddInitKind
		memset(&basic_globals.user_filter_map, 0, sizeof (*(&basic_globals.user_filter_map)));
		}
		#endif
		#ifdef __COMPILE_53
		else if (__choose0 == 54)
		{
		//AddInitKind
		memset(&basic_globals.user_shutdown_function_names, 0, sizeof (*(&basic_globals.user_shutdown_function_names)));
		}
		#endif
		#ifdef __COMPILE_54
		else if (__choose0 == 55)
		{
		//AddInitKind
		memset(&basic_globals.user_tick_functions, 0, sizeof (*(&basic_globals.user_tick_functions)));
		}
		#endif
		#ifdef __COMPILE_55
		else if (__choose0 == 56)
		{
		//AddInitKind
		memset(&ctx->active, 0, sizeof (*(&ctx->active)));
		}
		#endif
		#ifdef __COMPILE_56
		else if (__choose0 == 57)
		{
		//AddInitKind
		memset(&ctx->arg, 0, sizeof (*(&ctx->arg)));
		}
		#endif
		#ifdef __COMPILE_57
		else if (__choose0 == 58)
		{
		//AddInitKind
		memset(&ctx->buf, 0, sizeof (*(&ctx->buf)));
		}
		#endif
		#ifdef __COMPILE_58
		else if (__choose0 == 59)
		{
		//AddInitKind
		memset(&ctx->buf.a, 0, sizeof (*(&ctx->buf.a)));
		}
		#endif
		#ifdef __COMPILE_59
		else if (__choose0 == 60)
		{
		//AddInitKind
		memset(&ctx->buf.c, 0, sizeof (*(&ctx->buf.c)));
		}
		#endif
		#ifdef __COMPILE_60
		else if (__choose0 == 61)
		{
		//AddInitKind
		memset(&ctx->buf.len, 0, sizeof (*(&ctx->buf.len)));
		}
		#endif
		#ifdef __COMPILE_61
		else if (__choose0 == 62)
		{
		//AddInitKind
		memset(&ctx->form_app, 0, sizeof (*(&ctx->form_app)));
		}
		#endif
		#ifdef __COMPILE_62
		else if (__choose0 == 63)
		{
		//AddInitKind
		memset(&ctx->lookup_data, 0, sizeof (*(&ctx->lookup_data)));
		}
		#endif
		#ifdef __COMPILE_63
		else if (__choose0 == 64)
		{
		//AddInitKind
		memset(&ctx->result, 0, sizeof (*(&ctx->result)));
		}
		#endif
		#ifdef __COMPILE_64
		else if (__choose0 == 65)
		{
		//AddInitKind
		memset(&ctx->state, 0, sizeof (*(&ctx->state)));
		}
		#endif
		#ifdef __COMPILE_65
		else if (__choose0 == 66)
		{
		//AddInitKind
		memset(&ctx->tag, 0, sizeof (*(&ctx->tag)));
		}
		#endif
		#ifdef __COMPILE_66
		else if (__choose0 == 67)
		{
		//AddInitKind
		memset(&ctx->tags, 0, sizeof (*(&ctx->tags)));
		}
		#endif
		#ifdef __COMPILE_67
		else if (__choose0 == 68)
		{
		//AddInitKind
		memset(&ctx->url_app, 0, sizeof (*(&ctx->url_app)));
		}
		#endif
		#ifdef __COMPILE_68
		else if (__choose0 == 69)
		{
		//AddInitKind
		memset(&ctx->val, 0, sizeof (*(&ctx->val)));
		}
		#endif
		#ifdef __COMPILE_69
		else if (__choose0 == 70)
		{
		//AddInitKind
		memset((basic_globals.url_adapt_state_ex).lookup_data, 0, sizeof (*((basic_globals.url_adapt_state_ex).lookup_data)));
		}
		#endif
		#ifdef __COMPILE_70
		else if (__choose0 == 71)
		{
		//AddInitKind
		memset((basic_globals.url_adapt_state_ex).tags, 0, sizeof (*((basic_globals.url_adapt_state_ex).tags)));
		}
		#endif
		#ifdef __COMPILE_71
		else if (__choose0 == 72)
		{
		//AddInitKind
		memset((basic_globals.url_adapt_state_ex).url_app.c, 0, sizeof (*((basic_globals.url_adapt_state_ex).url_app.c)));
		}
		#endif
		#ifdef __COMPILE_72
		else if (__choose0 == 73)
		{
		//AddInitKind
		memset(basic_globals.CurrentLStatFile, 0, sizeof (*(basic_globals.CurrentLStatFile)));
		}
		#endif
		#ifdef __COMPILE_73
		else if (__choose0 == 74)
		{
		//AddInitKind
		memset(basic_globals.CurrentStatFile, 0, sizeof (*(basic_globals.CurrentStatFile)));
		}
		#endif
		#ifdef __COMPILE_74
		else if (__choose0 == 75)
		{
		//AddInitKind
		memset(basic_globals.active_ini_file_section, 0, sizeof (*(basic_globals.active_ini_file_section)));
		}
		#endif
		#ifdef __COMPILE_75
		else if (__choose0 == 76)
		{
		//AddInitKind
		memset(basic_globals.incomplete_class, 0, sizeof (*(basic_globals.incomplete_class)));
		}
		#endif
		#ifdef __COMPILE_76
		else if (__choose0 == 77)
		{
		//AddInitKind
		memset(basic_globals.locale_string, 0, sizeof (*(basic_globals.locale_string)));
		}
		#endif
		#ifdef __COMPILE_77
		else if (__choose0 == 78)
		{
		//AddInitKind
		memset(basic_globals.mmap_file, 0, sizeof (*(basic_globals.mmap_file)));
		}
		#endif
		#ifdef __COMPILE_78
		else if (__choose0 == 79)
		{
		//AddInitKind
		memset(basic_globals.next, 0, sizeof (*(basic_globals.next)));
		}
		#endif
		#ifdef __COMPILE_79
		else if (__choose0 == 80)
		{
		//AddInitKind
		memset(basic_globals.strtok_last, 0, sizeof (*(basic_globals.strtok_last)));
		}
		#endif
		#ifdef __COMPILE_80
		else if (__choose0 == 81)
		{
		//AddInitKind
		memset(basic_globals.strtok_string, 0, sizeof (*(basic_globals.strtok_string)));
		}
		#endif
		#ifdef __COMPILE_81
		else if (__choose0 == 82)
		{
		//AddInitKind
		memset(basic_globals.strtok_zval, 0, sizeof (*(basic_globals.strtok_zval)));
		}
		#endif
		#ifdef __COMPILE_82
		else if (__choose0 == 83)
		{
		//AddInitKind
		memset(basic_globals.syslog_device, 0, sizeof (*(basic_globals.syslog_device)));
		}
		#endif
		#ifdef __COMPILE_83
		else if (__choose0 == 84)
		{
		//AddInitKind
		memset(basic_globals.user_filter_map, 0, sizeof (*(basic_globals.user_filter_map)));
		}
		#endif
		#ifdef __COMPILE_84
		else if (__choose0 == 85)
		{
		//AddInitKind
		memset(basic_globals.user_shutdown_function_names, 0, sizeof (*(basic_globals.user_shutdown_function_names)));
		}
		#endif
		#ifdef __COMPILE_85
		else if (__choose0 == 86)
		{
		//AddInitKind
		memset(basic_globals.user_tick_functions, 0, sizeof (*(basic_globals.user_tick_functions)));
		}
		#endif
		#ifdef __COMPILE_86
		else if (__choose0 == 87)
		{
		//AddInitKind
		memset(ctx, 0, sizeof (*(ctx)));
		}
		#endif
		#ifdef __COMPILE_87
		else if (__choose0 == 88)
		{
		//AddInitKind
		memset(ctx->buf.c, 0, sizeof (*(ctx->buf.c)));
		}
		#endif
		#ifdef __COMPILE_88
		else if (__choose0 == 89)
		{
		//AddInitKind
		memset(ctx->lookup_data, 0, sizeof (*(ctx->lookup_data)));
		}
		#endif
		#ifdef __COMPILE_89
		else if (__choose0 == 90)
		{
		//AddInitKind
		memset(ctx->tags, 0, sizeof (*(ctx->tags)));
		}
		#endif
		#ifdef __COMPILE_90
		else if (__choose0 == 91)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (-1);
		}
		#endif
		#ifdef __COMPILE_91
		else if (__choose0 == 92)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (-2);
		}
		#endif
		#ifdef __COMPILE_92
		else if (__choose0 == 93)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (0);
		}
		#endif
		#ifdef __COMPILE_93
		else if (__choose0 == 94)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (1);
		}
		#endif
		#ifdef __COMPILE_94
		else if (__choose0 == 95)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (12);
		}
		#endif
		#ifdef __COMPILE_95
		else if (__choose0 == 96)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (128);
		}
		#endif
		#ifdef __COMPILE_96
		else if (__choose0 == 97)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (2);
		}
		#endif
		#ifdef __COMPILE_97
		else if (__choose0 == 98)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (2147483647);
		}
		#endif
		#ifdef __COMPILE_98
		else if (__choose0 == 99)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (4);
		}
		#endif
		#ifdef __COMPILE_99
		else if (__choose0 == 100)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (78);
		}
		#endif
		#ifdef __COMPILE_100
		else if (__choose0 == 101)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (8);
		}
		#endif
		#ifdef __COMPILE_101
		else if (__choose0 == 102)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).active = (mode);
		}
		#endif
		#ifdef __COMPILE_102
		else if (__choose0 == 103)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.c = (0);
		}
		#endif
		#ifdef __COMPILE_103
		else if (__choose0 == 104)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.c = (output);
		}
		#endif
		#ifdef __COMPILE_104
		else if (__choose0 == 105)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (-1);
		}
		#endif
		#ifdef __COMPILE_105
		else if (__choose0 == 106)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (-2);
		}
		#endif
		#ifdef __COMPILE_106
		else if (__choose0 == 107)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (0);
		}
		#endif
		#ifdef __COMPILE_107
		else if (__choose0 == 108)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (1);
		}
		#endif
		#ifdef __COMPILE_108
		else if (__choose0 == 109)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (12);
		}
		#endif
		#ifdef __COMPILE_109
		else if (__choose0 == 110)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (128);
		}
		#endif
		#ifdef __COMPILE_110
		else if (__choose0 == 111)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (2);
		}
		#endif
		#ifdef __COMPILE_111
		else if (__choose0 == 112)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (2147483647);
		}
		#endif
		#ifdef __COMPILE_112
		else if (__choose0 == 113)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (4);
		}
		#endif
		#ifdef __COMPILE_113
		else if (__choose0 == 114)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (78);
		}
		#endif
		#ifdef __COMPILE_114
		else if (__choose0 == 115)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (8);
		}
		#endif
		#ifdef __COMPILE_115
		else if (__choose0 == 116)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).form_app.len = (len);
		}
		#endif
		#ifdef __COMPILE_116
		else if (__choose0 == 117)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.c = (0);
		}
		#endif
		#ifdef __COMPILE_117
		else if (__choose0 == 118)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.c = (output);
		}
		#endif
		#ifdef __COMPILE_118
		else if (__choose0 == 119)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (-1);
		}
		#endif
		#ifdef __COMPILE_119
		else if (__choose0 == 120)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (-2);
		}
		#endif
		#ifdef __COMPILE_120
		else if (__choose0 == 121)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (0);
		}
		#endif
		#ifdef __COMPILE_121
		else if (__choose0 == 122)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (1);
		}
		#endif
		#ifdef __COMPILE_122
		else if (__choose0 == 123)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (12);
		}
		#endif
		#ifdef __COMPILE_123
		else if (__choose0 == 124)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (128);
		}
		#endif
		#ifdef __COMPILE_124
		else if (__choose0 == 125)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (2);
		}
		#endif
		#ifdef __COMPILE_125
		else if (__choose0 == 126)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (2147483647);
		}
		#endif
		#ifdef __COMPILE_126
		else if (__choose0 == 127)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (4);
		}
		#endif
		#ifdef __COMPILE_127
		else if (__choose0 == 128)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (78);
		}
		#endif
		#ifdef __COMPILE_128
		else if (__choose0 == 129)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (8);
		}
		#endif
		#ifdef __COMPILE_129
		else if (__choose0 == 130)
		{
		//AddStmtAndReplaceAtomKind
		(basic_globals.url_adapt_state_ex).url_app.len = (len);
		}
		#endif
		#ifdef __COMPILE_130
		else if (__choose0 == 131)
		{
		//AddStmtAndReplaceAtomKind
		(output)++;
		}
		#endif
		#ifdef __COMPILE_131
		else if (__choose0 == 132)
		{
		//AddStmtAndReplaceAtomKind
		++(output);
		}
		#endif
		#ifdef __COMPILE_132
		else if (__choose0 == 133)
		{
		//AddStmtAndReplaceAtomKind
		--(output);
		}
		#endif
		#ifdef __COMPILE_133
		else if (__choose0 == 134)
		{
		//AddStmtAndReplaceAtomKind
		_efree(((output)));
		}
		#endif
		#ifdef __COMPILE_134
		else if (__choose0 == 135)
		{
		//AddStmtAndReplaceAtomKind
		_zend_hash_init(((ctx)->tags), (0), (((void *)0)), (((void *)0)), (1));
		}
		#endif
		#ifdef __COMPILE_135
		else if (__choose0 == 136)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.c = (output);
		}
		#endif
		#ifdef __COMPILE_136
		else if (__choose0 == 137)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (-1);
		}
		#endif
		#ifdef __COMPILE_137
		else if (__choose0 == 138)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (-2);
		}
		#endif
		#ifdef __COMPILE_138
		else if (__choose0 == 139)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (0);
		}
		#endif
		#ifdef __COMPILE_139
		else if (__choose0 == 140)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (1);
		}
		#endif
		#ifdef __COMPILE_140
		else if (__choose0 == 141)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (12);
		}
		#endif
		#ifdef __COMPILE_141
		else if (__choose0 == 142)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (128);
		}
		#endif
		#ifdef __COMPILE_142
		else if (__choose0 == 143)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (2);
		}
		#endif
		#ifdef __COMPILE_143
		else if (__choose0 == 144)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (2147483647);
		}
		#endif
		#ifdef __COMPILE_144
		else if (__choose0 == 145)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (4);
		}
		#endif
		#ifdef __COMPILE_145
		else if (__choose0 == 146)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (78);
		}
		#endif
		#ifdef __COMPILE_146
		else if (__choose0 == 147)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (8);
		}
		#endif
		#ifdef __COMPILE_147
		else if (__choose0 == 148)
		{
		//AddStmtAndReplaceAtomKind
		ctx->result.len = (len);
		}
		#endif
		#ifdef __COMPILE_148
		else if (__choose0 == 149)
		{
		//AddStmtAndReplaceAtomKind
		len = (-1);
		}
		#endif
		#ifdef __COMPILE_149
		else if (__choose0 == 150)
		{
		//AddStmtAndReplaceAtomKind
		len = (-2);
		}
		#endif
		#ifdef __COMPILE_150
		else if (__choose0 == 151)
		{
		//AddStmtAndReplaceAtomKind
		len = (0);
		}
		#endif
		#ifdef __COMPILE_151
		else if (__choose0 == 152)
		{
		//AddStmtAndReplaceAtomKind
		len = (1);
		}
		#endif
		#ifdef __COMPILE_152
		else if (__choose0 == 153)
		{
		//AddStmtAndReplaceAtomKind
		len = (12);
		}
		#endif
		#ifdef __COMPILE_153
		else if (__choose0 == 154)
		{
		//AddStmtAndReplaceAtomKind
		len = (128);
		}
		#endif
		#ifdef __COMPILE_154
		else if (__choose0 == 155)
		{
		//AddStmtAndReplaceAtomKind
		len = (2);
		}
		#endif
		#ifdef __COMPILE_155
		else if (__choose0 == 156)
		{
		//AddStmtAndReplaceAtomKind
		len = (2147483647);
		}
		#endif
		#ifdef __COMPILE_156
		else if (__choose0 == 157)
		{
		//AddStmtAndReplaceAtomKind
		len = (4);
		}
		#endif
		#ifdef __COMPILE_157
		else if (__choose0 == 158)
		{
		//AddStmtAndReplaceAtomKind
		len = (78);
		}
		#endif
		#ifdef __COMPILE_158
		else if (__choose0 == 159)
		{
		//AddStmtAndReplaceAtomKind
		len = (8);
		}
		#endif
		#ifdef __COMPILE_159
		else if (__choose0 == 160)
		{
		//AddStmtAndReplaceAtomKind
		len = (len);
		}
		#endif
		#ifdef __COMPILE_160
		else if (__choose0 == 161)
		{
		//AddStmtAndReplaceAtomKind
		memset((ctx), 0, ((size_t)&((url_adapt_state_ex_t *)0)->tags));
		}
		#endif
		#ifdef __COMPILE_161
		else if (__choose0 == 162)
		{
		//AddStmtAndReplaceAtomKind
		zend_hash_destroy((ctx)->tags);
		}
		#endif
		#ifdef __COMPILE_162
		else if (__choose0 == 163)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).active = 0;
		}
		#endif
		#ifdef __COMPILE_163
		else if (__choose0 == 164)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).active = 1;
		}
		#endif
		#ifdef __COMPILE_164
		else if (__choose0 == 165)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).form_app.c = 0;
		}
		#endif
		#ifdef __COMPILE_165
		else if (__choose0 == 166)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).form_app.len = 0;
		}
		#endif
		#ifdef __COMPILE_166
		else if (__choose0 == 167)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).tags = ((void *)0);
		}
		#endif
		#ifdef __COMPILE_167
		else if (__choose0 == 168)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).url_app.c = 0;
		}
		#endif
		#ifdef __COMPILE_168
		else if (__choose0 == 169)
		{
		//AddStmtKind
		(basic_globals.url_adapt_state_ex).url_app.len = 0;
		}
		#endif
		#ifdef __COMPILE_169
		else if (__choose0 == 170)
		{
		//AddStmtKind
		(executor_globals.argument_stack) = zend_vm_stack_new_page(((16 * 1024) - 16));
		}
		#endif
		#ifdef __COMPILE_170
		else if (__choose0 == 171)
		{
		//AddStmtKind
		ctx->result.c = ((void *)0);
		}
		#endif
		#ifdef __COMPILE_171
		else if (__choose0 == 172)
		{
		//AddStmtKind
		ctx->result.len = 0;
		}
		#endif
		#ifdef __COMPILE_172
		else if (__choose0 == 173)
		{
		//AddStmtKind
		exit(1);
		}
		#endif
		#ifdef __COMPILE_173
		else if (__choose0 == 174)
		{
		//AddStmtKind
		len = (2147483647 * 2U + 1U);
		}
		#endif
		#ifdef __COMPILE_174
		else if (__choose0 == 175)
		{
		//AddStmtKind
		php_output_start_internal(("URL-Rewriter"), (sizeof ("URL-Rewriter") - 1), php_url_scanner_output_handler, 0, 112);
		}
		#endif
		#ifdef __COMPILE_175
		else if (__choose0 == 176)
		{
		//AddStmtKind
		php_url_scanner_ex_activate();
		}
		#endif
		#ifdef __COMPILE_176
		else if (__choose0 == 177)
		{
		//AddStmtKind
		php_url_scanner_ex_deactivate();
		}
		#endif
		#ifdef __COMPILE_177
		else if (__choose0 == 178)
		{
		//AddStmtKind
		zend_error((1 << 3L), "A non well formed numeric value encountered");
		}
		#endif
		#ifdef __COMPILE_178
		else if (__choose0 == 179)
		{
		//IfExitKind
		if (__is_neg("0-179", "L1005", 72, &(ctx), sizeof (ctx), &(ctx->buf.len),
					 sizeof (ctx->buf.len), &(ctx->buf.c), sizeof (ctx->buf.c), &(output), sizeof (output), &(output_len),
					 sizeof (output_len), &(handled_output_len), sizeof (handled_output_len), &(len), sizeof (len), &(handled_output),
					 sizeof (handled_output), &(mode), sizeof (mode), &((basic_globals.url_adapt_state_ex).active), sizeof ((basic_globals.url_adapt_state_ex).active), &((basic_globals.url_adapt_state_ex).lookup_data),
					 sizeof ((basic_globals.url_adapt_state_ex).lookup_data), &((basic_globals.url_adapt_state_ex).state), sizeof ((basic_globals.url_adapt_state_ex).state), &((basic_globals.url_adapt_state_ex).tags), sizeof ((basic_globals.url_adapt_state_ex).tags), &(basic_globals.user_shutdown_function_names),
					 sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string),
					 sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions),
					 sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid),
					 sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile),
					 sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left),
					 sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded),
					 sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file),
					 sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask),
					 sizeof (basic_globals.umask), &(basic_globals.url_adapt_state_ex.active), sizeof (basic_globals.url_adapt_state_ex.active), &(basic_globals.url_adapt_state_ex.lookup_data), sizeof (basic_globals.url_adapt_state_ex.lookup_data), &(basic_globals.url_adapt_state_ex.state),
					 sizeof (basic_globals.url_adapt_state_ex.state), &(basic_globals.url_adapt_state_ex.tags), sizeof (basic_globals.url_adapt_state_ex.tags), &(ctx->active), sizeof (ctx->active), &(ctx->lookup_data),
					 sizeof (ctx->lookup_data), &(ctx->state), sizeof (ctx->state), &(ctx->tags), sizeof (ctx->tags), &(ctx->buf.a),
					 sizeof (ctx->buf.a), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string),
					 sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len),
					 sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid),
					 sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime),
					 sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next),
					 sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded),
					 sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class),
					 sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map),
					 sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask)))
		    return;
		}
		#endif
		int __choose1 = __choose("__SWITCH1");
		{
		int __temp1=(ctx->buf.len) ;
		if (__choose1 == 0)
		{}
		#ifdef __COMPILE_179
		else if (__choose1 == 1)
		{
		__temp1= (__is_neg("1-1", "L1005", 72, &(ctx), sizeof (ctx), &(ctx->buf.len), sizeof (ctx->buf.len), &(ctx->buf.c), sizeof (ctx->buf.c), &(output), sizeof (output), &(output_len), sizeof (output_len), &(handled_output_len), sizeof (handled_output_len), &(len), sizeof (len), &(handled_output), sizeof (handled_output), &(mode), sizeof (mode), &((basic_globals.url_adapt_state_ex).active), sizeof ((basic_globals.url_adapt_state_ex).active), &((basic_globals.url_adapt_state_ex).lookup_data), sizeof ((basic_globals.url_adapt_state_ex).lookup_data), &((basic_globals.url_adapt_state_ex).state), sizeof ((basic_globals.url_adapt_state_ex).state), &((basic_globals.url_adapt_state_ex).tags), sizeof ((basic_globals.url_adapt_state_ex).tags), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask), &(basic_globals.url_adapt_state_ex.active), sizeof (basic_globals.url_adapt_state_ex.active), &(basic_globals.url_adapt_state_ex.lookup_data), sizeof (basic_globals.url_adapt_state_ex.lookup_data), &(basic_globals.url_adapt_state_ex.state), sizeof (basic_globals.url_adapt_state_ex.state), &(basic_globals.url_adapt_state_ex.tags), sizeof (basic_globals.url_adapt_state_ex.tags), &(ctx->active), sizeof (ctx->active), &(ctx->lookup_data), sizeof (ctx->lookup_data), &(ctx->state), sizeof (ctx->state), &(ctx->tags), sizeof (ctx->tags), &(ctx->buf.a), sizeof (ctx->buf.a), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask)));
		}
		#endif
		#ifdef __COMPILE_180
		else if (__choose1 == 2)
		{
		__temp1= ((ctx->buf.len) || __is_neg("1-2", "L1005", 72, &(ctx), sizeof (ctx), &(ctx->buf.len), sizeof (ctx->buf.len), &(ctx->buf.c), sizeof (ctx->buf.c), &(output), sizeof (output), &(output_len), sizeof (output_len), &(handled_output_len), sizeof (handled_output_len), &(len), sizeof (len), &(handled_output), sizeof (handled_output), &(mode), sizeof (mode), &((basic_globals.url_adapt_state_ex).active), sizeof ((basic_globals.url_adapt_state_ex).active), &((basic_globals.url_adapt_state_ex).lookup_data), sizeof ((basic_globals.url_adapt_state_ex).lookup_data), &((basic_globals.url_adapt_state_ex).state), sizeof ((basic_globals.url_adapt_state_ex).state), &((basic_globals.url_adapt_state_ex).tags), sizeof ((basic_globals.url_adapt_state_ex).tags), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask), &(basic_globals.url_adapt_state_ex.active), sizeof (basic_globals.url_adapt_state_ex.active), &(basic_globals.url_adapt_state_ex.lookup_data), sizeof (basic_globals.url_adapt_state_ex.lookup_data), &(basic_globals.url_adapt_state_ex.state), sizeof (basic_globals.url_adapt_state_ex.state), &(basic_globals.url_adapt_state_ex.tags), sizeof (basic_globals.url_adapt_state_ex.tags), &(ctx->active), sizeof (ctx->active), &(ctx->lookup_data), sizeof (ctx->lookup_data), &(ctx->state), sizeof (ctx->state), &(ctx->tags), sizeof (ctx->tags), &(ctx->buf.a), sizeof (ctx->buf.a), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask)));
		}
		#endif
		#ifdef __COMPILE_181
		else if (__choose1 == 3)
		{
		__temp1= ((ctx->buf.len) && !__is_neg("1-3", "L1005", 72, &(ctx), sizeof (ctx), &(ctx->buf.len), sizeof (ctx->buf.len), &(ctx->buf.c), sizeof (ctx->buf.c), &(output), sizeof (output), &(output_len), sizeof (output_len), &(handled_output_len), sizeof (handled_output_len), &(len), sizeof (len), &(handled_output), sizeof (handled_output), &(mode), sizeof (mode), &((basic_globals.url_adapt_state_ex).active), sizeof ((basic_globals.url_adapt_state_ex).active), &((basic_globals.url_adapt_state_ex).lookup_data), sizeof ((basic_globals.url_adapt_state_ex).lookup_data), &((basic_globals.url_adapt_state_ex).state), sizeof ((basic_globals.url_adapt_state_ex).state), &((basic_globals.url_adapt_state_ex).tags), sizeof ((basic_globals.url_adapt_state_ex).tags), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask), &(basic_globals.url_adapt_state_ex.active), sizeof (basic_globals.url_adapt_state_ex.active), &(basic_globals.url_adapt_state_ex.lookup_data), sizeof (basic_globals.url_adapt_state_ex.lookup_data), &(basic_globals.url_adapt_state_ex.state), sizeof (basic_globals.url_adapt_state_ex.state), &(basic_globals.url_adapt_state_ex.tags), sizeof (basic_globals.url_adapt_state_ex.tags), &(ctx->active), sizeof (ctx->active), &(ctx->lookup_data), sizeof (ctx->lookup_data), &(ctx->state), sizeof (ctx->state), &(ctx->tags), sizeof (ctx->tags), &(ctx->buf.a), sizeof (ctx->buf.a), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask)));
		}
		#endif
		int __choose2 = __choose("__SWITCH2");
		if (__choose2 == 0)
		{
		if (__temp1) {
					smart_str_appendl(&ctx->result, ctx->buf.c, ctx->buf.len);
					smart_str_appendl(&ctx->result, output, output_len);
		
					*handled_output = ctx->result.c;
					*handled_output_len = ctx->buf.len + output_len;
		
					ctx->result.c = NULL;
					ctx->result.len = 0;
					smart_str_free(&ctx->buf);
				} else {
					*handled_output = NULL;
				}
		
		}
		#ifdef __COMPILE_182
		else if (__choose2 == 1)
		{
		//GuardKind
		if (!__is_neg("2-1", "L1005", 72, &(ctx), sizeof (ctx), &(ctx->buf.len), sizeof (ctx->buf.len), &(ctx->buf.c), sizeof (ctx->buf.c), &(output), sizeof (output), &(output_len), sizeof (output_len), &(handled_output_len), sizeof (handled_output_len), &(len), sizeof (len), &(handled_output), sizeof (handled_output), &(mode), sizeof (mode), &((basic_globals.url_adapt_state_ex).active), sizeof ((basic_globals.url_adapt_state_ex).active), &((basic_globals.url_adapt_state_ex).lookup_data), sizeof ((basic_globals.url_adapt_state_ex).lookup_data), &((basic_globals.url_adapt_state_ex).state), sizeof ((basic_globals.url_adapt_state_ex).state), &((basic_globals.url_adapt_state_ex).tags), sizeof ((basic_globals.url_adapt_state_ex).tags), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask), &(basic_globals.url_adapt_state_ex.active), sizeof (basic_globals.url_adapt_state_ex.active), &(basic_globals.url_adapt_state_ex.lookup_data), sizeof (basic_globals.url_adapt_state_ex.lookup_data), &(basic_globals.url_adapt_state_ex.state), sizeof (basic_globals.url_adapt_state_ex.state), &(basic_globals.url_adapt_state_ex.tags), sizeof (basic_globals.url_adapt_state_ex.tags), &(ctx->active), sizeof (ctx->active), &(ctx->lookup_data), sizeof (ctx->lookup_data), &(ctx->state), sizeof (ctx->state), &(ctx->tags), sizeof (ctx->tags), &(ctx->buf.a), sizeof (ctx->buf.a), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask)))
		    if (ctx->buf.len) {
		        do {
		            register size_t __nl;
		            smart_str *__dest = (smart_str *)((&ctx->result));
		            do {
		                if (!(__dest)->c) {
		                    (__dest)->len = 0;
		                    __nl = (((ctx->buf.len)));
		                    (__dest)->a = __nl < 78 ? 78 : __nl + 128;
		                    (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		                } else {
		                    __nl = (__dest)->len + (((ctx->buf.len)));
		                    if (__nl >= (__dest)->a) {
		                        (__dest)->a = __nl + 128;
		                        (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		                    }
		                }
		            } while (0);
		            memcpy(__dest->c + __dest->len, ((ctx->buf.c)), ((ctx->buf.len)));
		            __dest->len = __nl;
		        } while (0);
		        do {
		            register size_t __nl;
		            smart_str *__dest = (smart_str *)((&ctx->result));
		            do {
		                if (!(__dest)->c) {
		                    (__dest)->len = 0;
		                    __nl = (((output_len)));
		                    (__dest)->a = __nl < 78 ? 78 : __nl + 128;
		                    (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		                } else {
		                    __nl = (__dest)->len + (((output_len)));
		                    if (__nl >= (__dest)->a) {
		                        (__dest)->a = __nl + 128;
		                        (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		                    }
		                }
		            } while (0);
		            memcpy(__dest->c + __dest->len, ((output)), ((output_len)));
		            __dest->len = __nl;
		        } while (0);
		        *handled_output = ctx->result.c;
		        *handled_output_len = ctx->buf.len + output_len;
		        ctx->result.c = ((void *)0);
		        ctx->result.len = 0;
		        do {
		            smart_str *__s = (smart_str *)((&ctx->buf));
		            if (__s->c) {
		                ((0) ? free(__s->c) : _efree((__s->c)));
		                __s->c = ((void *)0);
		            }
		            __s->a = __s->len = 0;
		        } while (0);
		    } else {
		        *handled_output = ((void *)0);
		    }
		
		}
		#endif
		#ifdef __COMPILE_183
		else if (__choose2 == 2)
		{
		//SpecialGuardKind
		if (!__is_neg("2-2", "L1005", 72, &(ctx), sizeof (ctx), &(ctx->buf.len), sizeof (ctx->buf.len), &(ctx->buf.c), sizeof (ctx->buf.c), &(output), sizeof (output), &(output_len), sizeof (output_len), &(handled_output_len), sizeof (handled_output_len), &(len), sizeof (len), &(handled_output), sizeof (handled_output), &(mode), sizeof (mode), &((basic_globals.url_adapt_state_ex).active), sizeof ((basic_globals.url_adapt_state_ex).active), &((basic_globals.url_adapt_state_ex).lookup_data), sizeof ((basic_globals.url_adapt_state_ex).lookup_data), &((basic_globals.url_adapt_state_ex).state), sizeof ((basic_globals.url_adapt_state_ex).state), &((basic_globals.url_adapt_state_ex).tags), sizeof ((basic_globals.url_adapt_state_ex).tags), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask), &(basic_globals.url_adapt_state_ex.active), sizeof (basic_globals.url_adapt_state_ex.active), &(basic_globals.url_adapt_state_ex.lookup_data), sizeof (basic_globals.url_adapt_state_ex.lookup_data), &(basic_globals.url_adapt_state_ex.state), sizeof (basic_globals.url_adapt_state_ex.state), &(basic_globals.url_adapt_state_ex.tags), sizeof (basic_globals.url_adapt_state_ex.tags), &(ctx->active), sizeof (ctx->active), &(ctx->lookup_data), sizeof (ctx->lookup_data), &(ctx->state), sizeof (ctx->state), &(ctx->tags), sizeof (ctx->tags), &(ctx->buf.a), sizeof (ctx->buf.a), &(basic_globals.user_shutdown_function_names), sizeof (basic_globals.user_shutdown_function_names), &(basic_globals.strtok_zval), sizeof (basic_globals.strtok_zval), &(basic_globals.strtok_string), sizeof (basic_globals.strtok_string), &(basic_globals.locale_string), sizeof (basic_globals.locale_string), &(basic_globals.strtok_last), sizeof (basic_globals.strtok_last), &(basic_globals.strtok_len), sizeof (basic_globals.strtok_len), &(basic_globals.user_tick_functions), sizeof (basic_globals.user_tick_functions), &(basic_globals.active_ini_file_section), sizeof (basic_globals.active_ini_file_section), &(basic_globals.page_uid), sizeof (basic_globals.page_uid), &(basic_globals.page_gid), sizeof (basic_globals.page_gid), &(basic_globals.page_inode), sizeof (basic_globals.page_inode), &(basic_globals.page_mtime), sizeof (basic_globals.page_mtime), &(basic_globals.CurrentStatFile), sizeof (basic_globals.CurrentStatFile), &(basic_globals.CurrentLStatFile), sizeof (basic_globals.CurrentLStatFile), &(basic_globals.next), sizeof (basic_globals.next), &(basic_globals.left), sizeof (basic_globals.left), &(basic_globals.rand_seed), sizeof (basic_globals.rand_seed), &(basic_globals.rand_is_seeded), sizeof (basic_globals.rand_is_seeded), &(basic_globals.mt_rand_is_seeded), sizeof (basic_globals.mt_rand_is_seeded), &(basic_globals.syslog_device), sizeof (basic_globals.syslog_device), &(basic_globals.incomplete_class), sizeof (basic_globals.incomplete_class), &(basic_globals.mmap_file), sizeof (basic_globals.mmap_file), &(basic_globals.mmap_len), sizeof (basic_globals.mmap_len), &(basic_globals.user_filter_map), sizeof (basic_globals.user_filter_map), &(basic_globals.umask), sizeof (basic_globals.umask)) && (ctx->buf.len)) {
		    do {
		        register size_t __nl;
		        smart_str *__dest = (smart_str *)((&ctx->result));
		        do {
		            if (!(__dest)->c) {
		                (__dest)->len = 0;
		                __nl = (((ctx->buf.len)));
		                (__dest)->a = __nl < 78 ? 78 : __nl + 128;
		                (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		            } else {
		                __nl = (__dest)->len + (((ctx->buf.len)));
		                if (__nl >= (__dest)->a) {
		                    (__dest)->a = __nl + 128;
		                    (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		                }
		            }
		        } while (0);
		        memcpy(__dest->c + __dest->len, ((ctx->buf.c)), ((ctx->buf.len)));
		        __dest->len = __nl;
		    } while (0);
		    do {
		        register size_t __nl;
		        smart_str *__dest = (smart_str *)((&ctx->result));
		        do {
		            if (!(__dest)->c) {
		                (__dest)->len = 0;
		                __nl = (((output_len)));
		                (__dest)->a = __nl < 78 ? 78 : __nl + 128;
		                (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		            } else {
		                __nl = (__dest)->len + (((output_len)));
		                if (__nl >= (__dest)->a) {
		                    (__dest)->a = __nl + 128;
		                    (__dest)->c = (((((0)))) ? __zend_realloc((((__dest)->c)), (((__dest)->a + 1))) : _erealloc(((((__dest)->c))), ((((__dest)->a + 1))), 0));
		                }
		            }
		        } while (0);
		        memcpy(__dest->c + __dest->len, ((output)), ((output_len)));
		        __dest->len = __nl;
		    } while (0);
		    *handled_output = ctx->result.c;
		    *handled_output_len = ctx->buf.len + output_len;
		    ctx->result.c = ((void *)0);
		    ctx->result.len = 0;
		    do {
		        smart_str *__s = (smart_str *)((&ctx->buf));
		        if (__s->c) {
		            ((0) ? free(__s->c) : _efree((__s->c)));
		            __s->c = ((void *)0);
		        }
		        __s->a = __s->len = 0;
		    } while (0);
		} else {
		    *handled_output = ((void *)0);
		}
		
		}
		#endif
		}
		}
	} else {
		*handled_output = NULL;
	}
}

PHPAPI int php_url_scanner_add_var(char *name, int name_len, char *value, int value_len, int urlencode TSRMLS_DC)
{
	char *encoded;
	int encoded_len;
	smart_str val;
	
	if (! BG(url_adapt_state_ex).active) {
		php_url_scanner_ex_activate(TSRMLS_C);
		php_output_start_internal(ZEND_STRL("URL-Rewriter"), php_url_scanner_output_handler, 0, PHP_OUTPUT_HANDLER_STDFLAGS TSRMLS_CC);
		BG(url_adapt_state_ex).active = 1;
	}


	if (BG(url_adapt_state_ex).url_app.len != 0) {
		smart_str_appends(&BG(url_adapt_state_ex).url_app, PG(arg_separator).output);
	}

	if (urlencode) {
		encoded = php_url_encode(value, value_len, &encoded_len);
		smart_str_setl(&val, encoded, encoded_len);
	} else {
		smart_str_setl(&val, value, value_len);
	}
	
	smart_str_appendl(&BG(url_adapt_state_ex).url_app, name, name_len);
	smart_str_appendc(&BG(url_adapt_state_ex).url_app, '=');
	smart_str_append(&BG(url_adapt_state_ex).url_app, &val);

	smart_str_appends(&BG(url_adapt_state_ex).form_app, "<input type=\"hidden\" name=\""); 
	smart_str_appendl(&BG(url_adapt_state_ex).form_app, name, name_len);
	smart_str_appends(&BG(url_adapt_state_ex).form_app, "\" value=\"");
	smart_str_append(&BG(url_adapt_state_ex).form_app, &val);
	smart_str_appends(&BG(url_adapt_state_ex).form_app, "\" />");

	if (urlencode)
		efree(encoded);

	return SUCCESS;
}

PHPAPI int php_url_scanner_reset_vars(TSRMLS_D)
{
	BG(url_adapt_state_ex).form_app.len = 0;
	BG(url_adapt_state_ex).url_app.len = 0;

	return SUCCESS;
}

PHP_MINIT_FUNCTION(url_scanner)
{
	BG(url_adapt_state_ex).tags = NULL;

	BG(url_adapt_state_ex).form_app.c = BG(url_adapt_state_ex).url_app.c = 0;
	BG(url_adapt_state_ex).form_app.len = BG(url_adapt_state_ex).url_app.len = 0;

	REGISTER_INI_ENTRIES();
	return SUCCESS;
}

PHP_MSHUTDOWN_FUNCTION(url_scanner)
{
	UNREGISTER_INI_ENTRIES();

	return SUCCESS;
}

PHP_RINIT_FUNCTION(url_scanner)
{
	BG(url_adapt_state_ex).active = 0;
	
	return SUCCESS;
}

PHP_RSHUTDOWN_FUNCTION(url_scanner)
{
	if (BG(url_adapt_state_ex).active) {
		php_url_scanner_ex_deactivate(TSRMLS_C);
		BG(url_adapt_state_ex).active = 0;
	}

	smart_str_free(&BG(url_adapt_state_ex).form_app);
	smart_str_free(&BG(url_adapt_state_ex).url_app);

	return SUCCESS;
}
