prog: bresenham.cpp
	echo /root/project/prophet-gpl/wrap/g++ -c bresenham.cpp $(CFLAGS) -o bresenham.o
	/root/project/prophet-gpl/wrap/g++ -c bresenham.cpp $(CFLAGS) -o bresenham.o
	/root/project/prophet-gpl/wrap/g++ $(CFLAGS) -o prog bresenham.o
